name: 'Flame Analyze'
description: 'An opinionated action that analyzes a Flutter project'
author: 'flame-engine'

branding:
  color: red
  icon: code

runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/scripts/analyze.sh
      shell: bash
